FROM arm64v8/centos:7

RUN yum update -y && yum -y install xmlstarlet saxon augeas bsdtar unzip java-1.8.0-openjdk-devel && yum clean all
RUN groupadd -r jboss -g 1000 && useradd -u 1000 -r -g jboss -m -d /opt/jboss -s /sbin/nologin -c "JBoss user" jboss &&     chmod 755 /opt/jboss
WORKDIR /opt/jboss
USER root

ENV JAVA_HOME=/usr/lib/jvm/java
ENV WILDFLY_VERSION=10.1.0.Final
ENV WILDFLY_SHA1=9ee3c0255e2e6007d502223916cefad2a1a5e333
ENV JBOSS_HOME=/opt/jboss/wildfly

RUN cd $HOME && curl -O https://download.jboss.org/wildfly/$WILDFLY_VERSION/wildfly-$WILDFLY_VERSION.tar.gz  && sha1sum wildfly-$WILDFLY_VERSION.tar.gz | grep $WILDFLY_SHA1     && tar xf wildfly-$WILDFLY_VERSION.tar.gz     && mv $HOME/wildfly-$WILDFLY_VERSION $JBOSS_HOME     && rm wildfly-$WILDFLY_VERSION.tar.gz     && chown -R jboss:0 ${JBOSS_HOME}     && chmod -R g+rw ${JBOSS_HOME}
ENV LAUNCH_JBOSS_IN_BACKGROUND=true
USER jboss
EXPOSE 8080
CMD ["/opt/jboss/wildfly/bin/standalone.sh" "-b" "0.0.0.0"]